package Interfaz;

import Mundo.Empresa;
import com.placeholder.PlaceHolder;
import java.awt.*;
import javax.swing.*;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author John Silva
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        initOtComponent(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoEmpresa = new javax.swing.ButtonGroup();
        jPanelIniciarSesión = new javax.swing.JPanel();
        jLabelImageUsuario = new javax.swing.JLabel();
        jLabelImageCode = new javax.swing.JLabel();
        jButtonVerContraseñaInicio = new javax.swing.JButton();
        jTextFieldNombreUsuarioInicio = new javax.swing.JTextField();
        jButtonCambiarApanelReg = new javax.swing.JButton();
        jButtonIniciarSesión = new javax.swing.JButton();
        jLabelO = new javax.swing.JLabel();
        tituloMuu = new javax.swing.JLabel();
        jLabelLogoMuu = new javax.swing.JLabel();
        jPasswordFieldInicio = new javax.swing.JPasswordField();
        jTextFieldInicioCodigoEmp = new javax.swing.JTextField();
        jTextFieldAuxContraseñaInicio = new javax.swing.JTextField();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jLabelImageLinea = new javax.swing.JLabel();
        jLabelImageLinea1 = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        jButtonVerConRegistro = new javax.swing.JButton();
        jLabelImageCorreo = new javax.swing.JLabel();
        jLabelImageUsuario2 = new javax.swing.JLabel();
        jLabelBienvenida = new javax.swing.JLabel();
        jTextFieldRegistroUsuario = new javax.swing.JTextField();
        jButtonCambiarApanelRegistro = new javax.swing.JButton();
        jButtonResgistrar = new javax.swing.JButton();
        jLabelAviso = new javax.swing.JLabel();
        jLabeljLabelImageMuuAmbas = new javax.swing.JLabel();
        jLabelImageMuLeche = new javax.swing.JLabel();
        jLabelImageMuuCarne = new javax.swing.JLabel();
        jCheckBoxMuuAmbas = new javax.swing.JCheckBox();
        jCheckBoxMuuCarne = new javax.swing.JCheckBox();
        jCheckBoxMuuLeche = new javax.swing.JCheckBox();
        jPasswordFieldRegistro = new javax.swing.JPasswordField();
        jTextFieldAuxContraseñaReg = new javax.swing.JTextField();
        jTextFieldRegistroCorreo = new javax.swing.JTextField();
        jLabelImageFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muu Seguro");
        setLocation(new java.awt.Point(150, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelIniciarSesión.setBackground(new java.awt.Color(0, 0, 0));
        jPanelIniciarSesión.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImageUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/Users.png"))); // NOI18N
        jPanelIniciarSesión.add(jLabelImageUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 220, 40, 30));

        jLabelImageCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/code.png"))); // NOI18N
        jPanelIniciarSesión.add(jLabelImageCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 170, 40, 30));

        jButtonVerContraseñaInicio.setForeground(new java.awt.Color(51, 51, 51));
        jButtonVerContraseñaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/view.png"))); // NOI18N
        jButtonVerContraseñaInicio.setContentAreaFilled(false);
        jButtonVerContraseñaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVerContraseñaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerContraseñaInicioActionPerformed(evt);
            }
        });
        jPanelIniciarSesión.add(jButtonVerContraseñaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 270, 40, 30));

        jTextFieldNombreUsuarioInicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldNombreUsuarioInicio.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldNombreUsuarioInicio.setAutoscrolls(false);
        jTextFieldNombreUsuarioInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldNombreUsuarioInicio.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldNombreUsuarioInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreUsuarioInicioKeyTyped(evt);
            }
        });
        jPanelIniciarSesión.add(jTextFieldNombreUsuarioInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 220, 329, 30));

        jButtonCambiarApanelReg.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCambiarApanelReg.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCambiarApanelReg.setForeground(new java.awt.Color(97, 97, 97));
        jButtonCambiarApanelReg.setText("Registrarse");
        jButtonCambiarApanelReg.setBorder(null);
        jButtonCambiarApanelReg.setBorderPainted(false);
        jButtonCambiarApanelReg.setFocusPainted(false);
        jButtonCambiarApanelReg.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonCambiarApanelReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarApanelRegActionPerformed(evt);
            }
        });
        jPanelIniciarSesión.add(jButtonCambiarApanelReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 440, 329, 32));

        jButtonIniciarSesión.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesión.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonIniciarSesión.setForeground(new java.awt.Color(97, 97, 97));
        jButtonIniciarSesión.setText("Iniciar Sesión");
        jButtonIniciarSesión.setBorder(null);
        jButtonIniciarSesión.setBorderPainted(false);
        jButtonIniciarSesión.setFocusPainted(false);
        jButtonIniciarSesión.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonIniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesiónActionPerformed(evt);
            }
        });
        jPanelIniciarSesión.add(jButtonIniciarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 380, 329, 32));

        jLabelO.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelO.setText("O");
        jLabelO.setToolTipText("");
        jPanelIniciarSesión.add(jLabelO, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 420, 10, -1));

        tituloMuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/MuuTitulo.png"))); // NOI18N
        tituloMuu.setText("jLabel8");
        jPanelIniciarSesión.add(tituloMuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 120, 230, 40));

        jLabelLogoMuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoMuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/logoMuuDef.png"))); // NOI18N
        jPanelIniciarSesión.add(jLabelLogoMuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, 90));

        jPasswordFieldInicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPasswordFieldInicio.setForeground(new java.awt.Color(97, 97, 97));
        jPasswordFieldInicio.setAutoscrolls(false);
        jPasswordFieldInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordFieldInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldInicioKeyTyped(evt);
            }
        });
        jPanelIniciarSesión.add(jPasswordFieldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 270, 329, 30));

        jTextFieldInicioCodigoEmp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldInicioCodigoEmp.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldInicioCodigoEmp.setAutoscrolls(false);
        jTextFieldInicioCodigoEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldInicioCodigoEmp.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldInicioCodigoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInicioCodigoEmpActionPerformed(evt);
            }
        });
        jTextFieldInicioCodigoEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldInicioCodigoEmpKeyTyped(evt);
            }
        });
        jPanelIniciarSesión.add(jTextFieldInicioCodigoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 170, 329, 30));

        jTextFieldAuxContraseñaInicio.setEditable(false);
        jTextFieldAuxContraseñaInicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldAuxContraseñaInicio.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldAuxContraseñaInicio.setAutoscrolls(false);
        jTextFieldAuxContraseñaInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldAuxContraseñaInicio.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanelIniciarSesión.add(jTextFieldAuxContraseñaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 270, 329, 30));

        jComboBoxRol.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxRol.setForeground(new java.awt.Color(97, 97, 97));
        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado", "Veterinario" }));
        jComboBoxRol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxRol.setFocusable(false);
        jPanelIniciarSesión.add(jComboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 320, 329, 30));

        jLabelImageLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/linea.png"))); // NOI18N
        jPanelIniciarSesión.add(jLabelImageLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 422, 150, 10));

        jLabelImageLinea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/linea.png"))); // NOI18N
        jPanelIniciarSesión.add(jLabelImageLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 422, 150, 10));

        getContentPane().add(jPanelIniciarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 400, 500));

        jPanelRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVerConRegistro.setForeground(new java.awt.Color(51, 51, 51));
        jButtonVerConRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/view.png"))); // NOI18N
        jButtonVerConRegistro.setContentAreaFilled(false);
        jButtonVerConRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVerConRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerConRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonVerConRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 220, 40, 30));

        jLabelImageCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/mail.png"))); // NOI18N
        jPanelRegistro.add(jLabelImageCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 120, 40, 30));

        jLabelImageUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/Users.png"))); // NOI18N
        jPanelRegistro.add(jLabelImageUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 170, 40, 30));

        jLabelBienvenida.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenida.setText("<html><center>Empieza a administrar tu empresa de la mejor manera. ");
        jLabelBienvenida.setToolTipText("");
        jPanelRegistro.add(jLabelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 100));

        jTextFieldRegistroUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldRegistroUsuario.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldRegistroUsuario.setAutoscrolls(false);
        jTextFieldRegistroUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldRegistroUsuario.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldRegistroUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRegistroUsuarioKeyTyped(evt);
            }
        });
        jPanelRegistro.add(jTextFieldRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 170, 329, 30));

        jButtonCambiarApanelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCambiarApanelRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCambiarApanelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiarApanelRegistro.setText("INICIAR SESIÓN");
        jButtonCambiarApanelRegistro.setToolTipText("");
        jButtonCambiarApanelRegistro.setBorder(null);
        jButtonCambiarApanelRegistro.setBorderPainted(false);
        jButtonCambiarApanelRegistro.setContentAreaFilled(false);
        jButtonCambiarApanelRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCambiarApanelRegistro.setFocusPainted(false);
        jButtonCambiarApanelRegistro.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonCambiarApanelRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarApanelRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonCambiarApanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 100, -1));

        jButtonResgistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonResgistrar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonResgistrar.setForeground(new java.awt.Color(97, 97, 97));
        jButtonResgistrar.setText("Continuar");
        jButtonResgistrar.setBorder(null);
        jButtonResgistrar.setBorderPainted(false);
        jButtonResgistrar.setFocusPainted(false);
        jButtonResgistrar.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonResgistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResgistrarActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonResgistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 400, 329, 32));

        jLabelAviso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelAviso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAviso.setText("¿Ya tienes una cuenta?");
        jLabelAviso.setToolTipText("");
        jPanelRegistro.add(jLabelAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 140, -1));

        jLabeljLabelImageMuuAmbas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelImageMuuAmbas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/logoMuuNegre.png"))); // NOI18N
        jPanelRegistro.add(jLabeljLabelImageMuuAmbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 90));

        jLabelImageMuLeche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageMuLeche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/logoMuuBlanco.png"))); // NOI18N
        jPanelRegistro.add(jLabelImageMuLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 80, 90));

        jLabelImageMuuCarne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageMuuCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/logoMuuColor.png"))); // NOI18N
        jPanelRegistro.add(jLabelImageMuuCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, 90));

        buttonGroupTipoEmpresa.add(jCheckBoxMuuAmbas);
        jCheckBoxMuuAmbas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxMuuAmbas.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMuuAmbas.setText("Doble");
        jCheckBoxMuuAmbas.setContentAreaFilled(false);
        jPanelRegistro.add(jCheckBoxMuuAmbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 270, 70, -1));

        buttonGroupTipoEmpresa.add(jCheckBoxMuuCarne);
        jCheckBoxMuuCarne.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxMuuCarne.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMuuCarne.setSelected(true);
        jCheckBoxMuuCarne.setText("Carne");
        jCheckBoxMuuCarne.setContentAreaFilled(false);
        jPanelRegistro.add(jCheckBoxMuuCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 270, 70, -1));

        buttonGroupTipoEmpresa.add(jCheckBoxMuuLeche);
        jCheckBoxMuuLeche.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxMuuLeche.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMuuLeche.setText("Leche");
        jCheckBoxMuuLeche.setContentAreaFilled(false);
        jPanelRegistro.add(jCheckBoxMuuLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 270, 70, -1));

        jPasswordFieldRegistro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPasswordFieldRegistro.setAutoscrolls(false);
        jPasswordFieldRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordFieldRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldRegistroKeyTyped(evt);
            }
        });
        jPanelRegistro.add(jPasswordFieldRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 220, 329, 30));

        jTextFieldAuxContraseñaReg.setEditable(false);
        jTextFieldAuxContraseñaReg.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldAuxContraseñaReg.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldAuxContraseñaReg.setAutoscrolls(false);
        jTextFieldAuxContraseñaReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldAuxContraseñaReg.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanelRegistro.add(jTextFieldAuxContraseñaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 220, 329, 30));

        jTextFieldRegistroCorreo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldRegistroCorreo.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldRegistroCorreo.setAutoscrolls(false);
        jTextFieldRegistroCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldRegistroCorreo.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldRegistroCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRegistroCorreoKeyTyped(evt);
            }
        });
        jPanelRegistro.add(jTextFieldRegistroCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 120, 329, 30));

        getContentPane().add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 400, 500));

        jLabelImageFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/fondoMuu.png"))); // NOI18N
        getContentPane().add(jLabelImageFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    /*s
    *Ver contraseña en inicio de sesión
    */
    private void jButtonVerContraseñaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerContraseñaInicioActionPerformed
        // TODO add your handling code here:
        counter+=1;
        verContraseñas(jTextFieldAuxContraseñaInicio,jPasswordFieldInicio);
    }//GEN-LAST:event_jButtonVerContraseñaInicioActionPerformed
    /*
    *Boton INICIAR SESIÓN 
    */
    private void jButtonIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesiónActionPerformed
        // TODO add your handling code here:
        String codigoEmp=jTextFieldInicioCodigoEmp.getText();
        String nombreUsuario=jTextFieldNombreUsuarioInicio.getText();
        String contraseña=String.valueOf(jPasswordFieldInicio.getPassword());
        String rol=(String)jComboBoxRol.getSelectedItem();
        if(comprobarCredencialesInicio(rol,codigoEmp, nombreUsuario,contraseña)){
            Empresa emp=new Empresa(codigoEmp);
            siguienteVentana();//Ignore esto
            //Dependiendo del tipo de usuario se dirige:
            //Administrador---->Ventana principal administrador
            if(rol.equals("Administrador")){
                siguienteVentana(); 
                Ventana ventanaPrincipalAdmin=new Ventana(emp);
                this.setVisible(false);
                ventanaPrincipalAdmin.setVisible(true);
            }else{
                //Empleado---->Ventana principal empleado
                //Veterinario---->Ventana principal veterinario
            }
        }else{//errores contraseñas,codigoEmp o usuarios incorrectos
             JOptionPane.showMessageDialog(null, "El usuario no ha sido encontrado, revise las credenciales", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIniciarSesiónActionPerformed
    /*
    *Boton CONTINUAR registro
    */
    private void jButtonResgistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResgistrarActionPerformed
        // TODO add your handling code here:
        String correoIngresado=jTextFieldRegistroCorreo.getText();
        String nombreUsuario=jTextFieldRegistroUsuario.getText();
        String tipoEmpresa=comprobarSelecciondeCheckBox();
        String contraseña=String.valueOf(jPasswordFieldRegistro.getPassword());
        if(comprobarCorreoRegistro(correoIngresado)){
            if(noEspaciosEnBlanco(nombreUsuario) && noEspaciosEnBlanco(contraseña)){
                    Empresa emp=new Empresa(tipoEmpresa, correoIngresado, nombreUsuario, contraseña);
                    siguienteVentana(); 
                    Ventana ventanaPrincipalAdmin=new Ventana(emp);
                    this.setVisible(false);
                    ventanaPrincipalAdmin.setVisible(true);
            }else{
                //error espacios en blanco
                JOptionPane.showMessageDialog(null, "No se permiten espacios vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        }else{
            //error correo existente o no posible
            jTextFieldRegistroCorreo.setBackground(Color.decode("#F9ABAB"));
            JOptionPane.showMessageDialog(null, "Correo inválido o existente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jButtonResgistrarActionPerformed

    
/*
*Cambiar a registro, limpiar todos los controles
*/
    private void jButtonCambiarApanelRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarApanelRegActionPerformed
        // TODO add your handling code here:
        jPanelIniciarSesión.setVisible(false);
        jPanelRegistro.setVisible(true);
        jTextFieldInicioCodigoEmp.setText("");
        jTextFieldNombreUsuarioInicio.setText("");
        jPasswordFieldInicio.setText("");
        jTextFieldAuxContraseñaInicio.setText("");
        holder=new PlaceHolder(jPasswordFieldInicio, "Contraseña");
        holder=new PlaceHolder(jTextFieldInicioCodigoEmp, "Código de la empresa");
        holder=new PlaceHolder(jTextFieldNombreUsuarioInicio, "Nombre de usuario");
    }//GEN-LAST:event_jButtonCambiarApanelRegActionPerformed
/*
*Cambiar a inicio de sesión, limpiar todos los controles
*/
    private void jButtonCambiarApanelRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarApanelRegistroActionPerformed
        // TODO add your handling code here:
        jPanelRegistro.setVisible(false);
        jPanelIniciarSesión.setVisible(true);
        jTextFieldRegistroCorreo.setText("");
        jTextFieldRegistroUsuario.setText("");
        jPasswordFieldRegistro.setText("");
        jTextFieldAuxContraseñaReg.setText("");
        holder=new PlaceHolder(jTextFieldRegistroCorreo, "Correo electrónico");
        holder=new PlaceHolder(jPasswordFieldRegistro, "Crear contraseña");
        holder=new PlaceHolder(jTextFieldRegistroUsuario, "Crear nombre de usuario");
    }//GEN-LAST:event_jButtonCambiarApanelRegistroActionPerformed
    /*
    *Ver contraseña en registro
    */
    private void jButtonVerConRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerConRegistroActionPerformed
        // TODO add your handling code here:
        counter+=1;
        verContraseñas(jTextFieldAuxContraseñaReg,jPasswordFieldRegistro);
    }//GEN-LAST:event_jButtonVerConRegistroActionPerformed

    private void jTextFieldInicioCodigoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInicioCodigoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInicioCodigoEmpActionPerformed

    /*
    *Eventos para evitar el ingreso de comas
    */
    private void jTextFieldInicioCodigoEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInicioCodigoEmpKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){ 
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jTextFieldInicioCodigoEmpKeyTyped

    private void jTextFieldNombreUsuarioInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioInicioKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){ 
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreUsuarioInicioKeyTyped

    private void jPasswordFieldInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldInicioKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){ 
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldInicioKeyTyped

    private void jTextFieldRegistroCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegistroCorreoKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){ 
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRegistroCorreoKeyTyped

    private void jTextFieldRegistroUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegistroUsuarioKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){ 
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRegistroUsuarioKeyTyped

    private void jPasswordFieldRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldRegistroKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){ 
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldRegistroKeyTyped
    /*
    *Fin de eventos ingreso de comas
    */
    
    
    /**
     * @param args the command line arguments
     */
    /*
    *Objeto para tener textFields con contenido presdeterminado
    */
    private PlaceHolder holder;
    /*
    *Contador para ver o no contraseña
    */
    private int counter;
    /*
    *Direccion del archivo .csv donde se almacenan los datos de las
    *empresas registradas
    */
    static private final String PATH=".\\src\\dataBase\\empresas.csv";
    /*
    *Direccion del archivo .csv donde se almacenan los datos de los
    *administradores perteneciantes a una cierta empresa 
    */
    private String pathUsers;
    
    //METODOS PROPIOS
    public void initOtComponent(){
        holder=new PlaceHolder(jPasswordFieldInicio, "Contraseña");
        holder=new PlaceHolder(jTextFieldInicioCodigoEmp, "Código de la empresa");
        holder=new PlaceHolder(jTextFieldNombreUsuarioInicio, "Nombre de usuario");
        holder=new PlaceHolder(jTextFieldRegistroCorreo, "Correo electrónico");
        holder=new PlaceHolder(jPasswordFieldRegistro, "Crear contraseña");
        holder=new PlaceHolder(jTextFieldRegistroUsuario, "Crear nombre de usuario");
        try{
            FileWriter empresas=new FileWriter(PATH, true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ups! Algo salió mal, inténtelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jPanelRegistro.setVisible(false);
    }
    /*
    Comprobar correo electrónico
    */
    private boolean comprobarCorreoRegistro(String correo){
        String linea;

        if((correo.indexOf('@')==-1) || (correo.indexOf('.')==-1) ){
                return false;
        } else {
        try{
            BufferedReader br =new BufferedReader(new FileReader(PATH));
            while((linea= br.readLine())!= null){//cada linea del archivo csv
                String[] valores = linea.split(",");//arreglo de las columnas de cada linea
                //
                if(valores[2].equals(correo)){//columna[2]=correosregistrados
                    return false;
                }
            }
            return true;
        }catch(Exception ex){
            return false;
        }
        }
    }
    /*
    *evitar registros en blanco
    */
    private boolean noEspaciosEnBlanco(String cadena){
        if (cadena.equals("Crear nombre de usuario")!=true && cadena.equals("Crear contraseña")!=true
            && cadena.equals("Contraseña")!=true && cadena.equals("Código de la empresa")!=true
            && cadena.equals("Nombre de usuario")!=true){
            return true;
        }else{
            return false;
        }
    }
     /*
    *ver las contraseñas de los JPasswordField
    */
    private void verContraseñas(javax.swing.JTextField auxiliar, javax.swing.JPasswordField panelContraseña ){
        if(counter%2!=0){
            panelContraseña.setVisible(false);
            auxiliar.setVisible(true);
            auxiliar.setText(panelContraseña.getText());
        }else{
            panelContraseña.setVisible(true);
            auxiliar.setVisible(false);
        }
    }
    
    /*
    *Retrorna el tipo empresa dependiendo de la seleccion del usuario
    */
    private String comprobarSelecciondeCheckBox(){
        if(jCheckBoxMuuAmbas.isSelected()){
            return "Doble";
        }else if(jCheckBoxMuuLeche.isSelected()){
            return "Leche";
        }else{
            return "Carne";
        }   
    }
    
    /*
    *Comprobar credenciales inicio de sesion
    */
    private boolean comprobarCredencialesInicio(String rol,String codigoEmp, String nombreUsuario, String contraseña){
       String linea;
   
       if(noEspaciosEnBlanco(codigoEmp) && noEspaciosEnBlanco(nombreUsuario)
            && noEspaciosEnBlanco(contraseña)){
            if(rol.equals("Administrador")){
                //Administrador
                try{
                    BufferedReader br =new BufferedReader(new FileReader(PATH));
                    while((linea=br.readLine())!= null){//cada linea del archivo csv
                        String[] valores = linea.split(",");//arreglo de las columnas de cada linea
                        if(valores[0].equals(codigoEmp) && valores[3].equals(nombreUsuario) && valores[4].equals(contraseña)){
                            return true;
                        }   
                    }
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ups! Algo salió mal, inténtelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }else{
                //empleado y veternario
               String correo="";
               /*Encontrar el correo perteneciente al codigo de la empresa
               *para ir al archivo .csv de usuarios
               */
                try{
                    BufferedReader br =new BufferedReader(new FileReader(PATH));
                    while((linea=br.readLine())!= null){//cada linea del archivo csv
                        String[] valores = linea.split(",");//arreglo de las columnas de cada linea
                        if(valores[0].equals(codigoEmp)){
                            correo=valores[2];
                            break;
                        }   
                    }     
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ups! Algo salió mal, inténtelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                /*
                *Establecer la ruta de busqueda para verificaciones
                */
                pathUsers=".\\src\\dataBase\\"+correo+"Usuarios.csv";
                /*
                *Buscar el usuario EMPLEADO o VETERINARIO
                */
                try{
                    BufferedReader br =new BufferedReader(new FileReader(pathUsers));
                    while((linea=br.readLine())!= null){//cada linea del archivo csv
                        String[] valores = linea.split(",");//arreglo de las columnas de cada linea
                        if(valores[0].equals(rol) && valores[2].equals(nombreUsuario) && valores[3].equals(contraseña)){
                            return true;
                        }   
                    }
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ups! Algo salió mal, inténtelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
        }else{
           return false;
       }
        return false;
    }
    
    private void siguienteVentana(){
        jPasswordFieldInicio.setText("");
        jTextFieldInicioCodigoEmp.setText("");
        jTextFieldNombreUsuarioInicio.setText("");
        jTextFieldRegistroCorreo.setText("");
        jTextFieldRegistroUsuario.setText("");
        jPasswordFieldRegistro.setText("");
        jTextFieldAuxContraseñaReg.setText("");
        jTextFieldAuxContraseñaInicio.setText("");
        holder=new PlaceHolder(jPasswordFieldInicio, "Contraseña");
        holder=new PlaceHolder(jTextFieldInicioCodigoEmp, "Código de la empresa");
        holder=new PlaceHolder(jTextFieldNombreUsuarioInicio, "Nombre de usuario");
        holder=new PlaceHolder(jTextFieldRegistroCorreo, "Correo electrónico");
        holder=new PlaceHolder(jPasswordFieldRegistro, "Crear contraseña");
        holder=new PlaceHolder(jTextFieldRegistroUsuario, "Crear nombre de usuario");
    }
    /*
    *Ingreso de comas en jTextField
    */
    private boolean ingresoCaracterSep(char caracter){
        if(caracter==','){    
            return true;
        }
        return false;
    }
 
    
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoEmpresa;
    private javax.swing.JButton jButtonCambiarApanelReg;
    private javax.swing.JButton jButtonCambiarApanelRegistro;
    private javax.swing.JButton jButtonIniciarSesión;
    private javax.swing.JButton jButtonResgistrar;
    private javax.swing.JButton jButtonVerConRegistro;
    private javax.swing.JButton jButtonVerContraseñaInicio;
    private javax.swing.JCheckBox jCheckBoxMuuAmbas;
    private javax.swing.JCheckBox jCheckBoxMuuCarne;
    private javax.swing.JCheckBox jCheckBoxMuuLeche;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelImageCode;
    private javax.swing.JLabel jLabelImageCorreo;
    private javax.swing.JLabel jLabelImageFondo;
    private javax.swing.JLabel jLabelImageLinea;
    private javax.swing.JLabel jLabelImageLinea1;
    private javax.swing.JLabel jLabelImageMuLeche;
    private javax.swing.JLabel jLabelImageMuuCarne;
    private javax.swing.JLabel jLabelImageUsuario;
    private javax.swing.JLabel jLabelImageUsuario2;
    private javax.swing.JLabel jLabelLogoMuu;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JLabel jLabeljLabelImageMuuAmbas;
    private javax.swing.JPanel jPanelIniciarSesión;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPasswordField jPasswordFieldInicio;
    private javax.swing.JPasswordField jPasswordFieldRegistro;
    private javax.swing.JTextField jTextFieldAuxContraseñaInicio;
    private javax.swing.JTextField jTextFieldAuxContraseñaReg;
    private javax.swing.JTextField jTextFieldInicioCodigoEmp;
    private javax.swing.JTextField jTextFieldNombreUsuarioInicio;
    private javax.swing.JTextField jTextFieldRegistroCorreo;
    private javax.swing.JTextField jTextFieldRegistroUsuario;
    private javax.swing.JLabel tituloMuu;
    // End of variables declaration//GEN-END:variables
    //Variables propias

}
