package Interfaz;

import Mundo.Empresa;
import javax.swing.JOptionPane;
import Mundo.Veterinario;
/**
 *
 * @author John Silva
 */
public class PerfilVeterinarios extends javax.swing.JFrame {

    /** Creates new form PerfilVeterinarios */
    public PerfilVeterinarios(Empresa emp,Veterinario vet) {
        empresa=emp;
        veterinario=vet;
       
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalPerfil = new javax.swing.JPanel();
        jPanelContenerdorNombres = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAbreviacionUsuario = new javax.swing.JLabel();
        jLabelCirculoPerfil = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelFondoSup = new javax.swing.JLabel();
        jButtonVerContraseña = new javax.swing.JButton();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabelNombreDeUsuario = new javax.swing.JLabel();
        jTextFieldNombreDeUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabelAvis = new javax.swing.JLabel();
        jLabelCodigoEmpresa = new javax.swing.JLabel();
        jLabelFechaVinculación = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelMisDatos = new javax.swing.JLabel();
        jTextFieldCodigoEmpresa = new javax.swing.JTextField();
        jLabelLinea = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jTextFieldAuxiliar = new javax.swing.JTextField();
        jToggleButtonModificar = new javax.swing.JToggleButton();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muu Seguro");
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipalPerfil.setBackground(new java.awt.Color(51, 51, 51));
        jPanelPrincipalPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jPanelPrincipalPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContenerdorNombres.setBackground(new java.awt.Color(102, 102, 102));
        jPanelContenerdorNombres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAbreviacionUsuario.setBackground(new java.awt.Color(239, 69, 200));
        jLabelAbreviacionUsuario.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jLabelAbreviacionUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAbreviacionUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbreviacionUsuario.setText(veterinario.darNombre().charAt(0)+"");
        jLabelAbreviacionUsuario.setToolTipText("");
        jPanel1.add(jLabelAbreviacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 12, 35, 65));

        jLabelCirculoPerfil.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCirculoPerfil.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelCirculoPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCirculoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCirculoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/circuloPerfilVete.png"))); // NOI18N
        jPanel1.add(jLabelCirculoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 65, 65));

        jLabelNombreUsuario.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUsuario.setText(veterinario.darNombre());
        jLabelNombreUsuario.setToolTipText("");
        jPanel1.add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jPanelContenerdorNombres.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 30, 250, 90));

        jLabelFondoSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/fondoVeterinario.jpg"))); // NOI18N
        jPanelContenerdorNombres.add(jLabelFondoSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 150));

        jPanelPrincipalPerfil.add(jPanelContenerdorNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 150));

        jButtonVerContraseña.setForeground(new java.awt.Color(51, 51, 51));
        jButtonVerContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/viewBlue.png"))); // NOI18N
        jButtonVerContraseña.setContentAreaFilled(false);
        jButtonVerContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerContraseñaActionPerformed(evt);
            }
        });
        jPanelPrincipalPerfil.add(jButtonVerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 330, 35, 30));

        jTextFieldSalario.setEditable(false);
        jTextFieldSalario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSalario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldSalario.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldSalario.setText("$"+veterinario.darSalario());
        jTextFieldSalario.setAutoscrolls(false);
        jTextFieldSalario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelPrincipalPerfil.add(jTextFieldSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 255, 200, 30));

        jLabelNombreDeUsuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelNombreDeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreDeUsuario.setText("Nombre de usuario");
        jLabelNombreDeUsuario.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 235, 200, -1));

        jTextFieldNombreDeUsuario.setEditable(false);
        jTextFieldNombreDeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreDeUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldNombreDeUsuario.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldNombreDeUsuario.setText(veterinario.darNombre());
        jTextFieldNombreDeUsuario.setAutoscrolls(false);
        jTextFieldNombreDeUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelPrincipalPerfil.add(jTextFieldNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 255, 200, 30));

        jLabelContraseña.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña");
        jLabelContraseña.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 200, -1));

        jTextFieldFecha.setEditable(false);
        jTextFieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldFecha.setText(veterinario.darFechaInicioLaboral());
        jTextFieldFecha.setAutoscrolls(false);
        jTextFieldFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldFecha.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanelPrincipalPerfil.add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 200, 30));

        jLabelAvis.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelAvis.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAvis.setText("¿Deseas modificar tus datos?");
        jLabelAvis.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelAvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 400, 170, -1));

        jLabelCodigoEmpresa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelCodigoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoEmpresa.setText("Código de la empresa");
        jLabelCodigoEmpresa.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelCodigoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, 200, -1));

        jLabelFechaVinculación.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelFechaVinculación.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaVinculación.setText("Fecha de vinculación laboral");
        jLabelFechaVinculación.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelFechaVinculación, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 220, -1));

        jLabelSalario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelSalario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalario.setText("Salario");
        jLabelSalario.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 235, 200, -1));

        jLabelMisDatos.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelMisDatos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMisDatos.setText("Mis Datos");
        jLabelMisDatos.setToolTipText("");
        jPanelPrincipalPerfil.add(jLabelMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, -1));

        jTextFieldCodigoEmpresa.setEditable(false);
        jTextFieldCodigoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoEmpresa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldCodigoEmpresa.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldCodigoEmpresa.setText(empresa.darCodigo());
        jTextFieldCodigoEmpresa.setAutoscrolls(false);
        jTextFieldCodigoEmpresa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldCodigoEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jTextFieldCodigoEmpresa.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanelPrincipalPerfil.add(jTextFieldCodigoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 255, 200, 30));

        jLabelLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/DataImage/lineaLarga.png"))); // NOI18N
        jPanelPrincipalPerfil.add(jLabelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 740, 20));

        jPasswordFieldContraseña.setEditable(false);
        jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPasswordFieldContraseña.setText(veterinario.darContraseña());
        jPanelPrincipalPerfil.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 30));

        jTextFieldAuxiliar.setEditable(false);
        jTextFieldAuxiliar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldAuxiliar.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldAuxiliar.setAutoscrolls(false);
        jTextFieldAuxiliar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelPrincipalPerfil.add(jTextFieldAuxiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 30));

        jToggleButtonModificar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jToggleButtonModificar.setForeground(new java.awt.Color(77, 144, 254));
        jToggleButtonModificar.setText("MODIFICAR DATOS");
        jToggleButtonModificar.setBorder(null);
        jToggleButtonModificar.setBorderPainted(false);
        jToggleButtonModificar.setContentAreaFilled(false);
        jToggleButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonModificar.setFocusPainted(false);
        jToggleButtonModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonModificarActionPerformed(evt);
            }
        });
        jPanelPrincipalPerfil.add(jToggleButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 400, -1, -1));

        jButtonRegresar.setBackground(new java.awt.Color(77, 144, 254));
        jButtonRegresar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setBorder(null);
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setOpaque(true);
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseExited(evt);
            }
        });
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanelPrincipalPerfil.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 30));

        getContentPane().add(jPanelPrincipalPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerContraseñaActionPerformed
        // TODO add your handling code here:
        counter += 1;
        verContraseña();
    }//GEN-LAST:event_jButtonVerContraseñaActionPerformed

    private void jToggleButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonModificarActionPerformed
        // TODO add your handling code here:
        modificable = true;
        if (jToggleButtonModificar.isSelected()) {
            jPasswordFieldContraseña.setEditable(true);
            jPasswordFieldContraseña.setBackground(new java.awt.Color(163, 194, 255));
        } else {
            jPasswordFieldContraseña.setEditable(false);
            jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_jToggleButtonModificarActionPerformed

    private void jButtonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseEntered
        jButtonRegresar.setBackground(new java.awt.Color(177, 207, 255));
    }//GEN-LAST:event_jButtonRegresarMouseEntered

    private void jButtonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseExited
        jButtonRegresar.setBackground(new java.awt.Color(77,144,254));
    }//GEN-LAST:event_jButtonRegresarMouseExited

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        if (modificable) {
            int respuesta = JOptionPane.showOptionDialog(this, "Desea guardar los cambios realizados", "Atención", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No", "Cancelar"}, "Si");
            if (respuesta != -1 && respuesta != 2) {
                if (respuesta == 0) {
                    empresa.darAdmin().modificarUsuario("Veterinario", Integer.parseInt(jTextFieldSalario.getText().substring(1, jTextFieldSalario.getText().length())), jLabelNombreUsuario.getText(), jPasswordFieldContraseña.getText(), jTextFieldFecha.getText());
                    this.setVisible(false);
                    empresa = new Empresa(jTextFieldCodigoEmpresa.getText());
                    VeterinarioInterfaz ventana = new VeterinarioInterfaz(empresa,veterinario.darNombre());
                    ventana.setVisible(true);
                } else if (respuesta == 1) {
                    this.setVisible(false);
                    VeterinarioInterfaz ventana = new VeterinarioInterfaz(empresa,veterinario.darNombre());
                    ventana.setVisible(true);
                }
            }
        } else {
            this.setVisible(false);
            VeterinarioInterfaz ventana = new VeterinarioInterfaz(empresa,veterinario.darNombre());
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    private int counter = 0;
    private boolean modificable = false;
    private Empresa empresa;
    private Veterinario veterinario;
    String codigoEmp;
    
    private void verContraseña() {
        if (counter % 2 != 0) {
            jPasswordFieldContraseña.setVisible(false);
            jTextFieldAuxiliar.setVisible(true);
            jTextFieldAuxiliar.setText(jPasswordFieldContraseña.getText());
        } else {
            jPasswordFieldContraseña.setVisible(true);
            jTextFieldAuxiliar.setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonVerContraseña;
    private javax.swing.JLabel jLabelAbreviacionUsuario;
    private javax.swing.JLabel jLabelAvis;
    private javax.swing.JLabel jLabelCirculoPerfil;
    private javax.swing.JLabel jLabelCodigoEmpresa;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelFechaVinculación;
    private javax.swing.JLabel jLabelFondoSup;
    private javax.swing.JLabel jLabelLinea;
    private javax.swing.JLabel jLabelMisDatos;
    private javax.swing.JLabel jLabelNombreDeUsuario;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContenerdorNombres;
    private javax.swing.JPanel jPanelPrincipalPerfil;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldAuxiliar;
    private javax.swing.JTextField jTextFieldCodigoEmpresa;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombreDeUsuario;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JToggleButton jToggleButtonModificar;
    // End of variables declaration//GEN-END:variables

}
