/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author John Silva
 */
import com.placeholder.PlaceHolder;
import javax.swing.JOptionPane;
import Mundo.Empresa;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author John Silva and Laura Ardila
 */
public class Registros extends javax.swing.JFrame {
    
    /**
     * Creates new form Registros
     */
    public Registros(Empresa emp) {
        initComponents(emp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Empresa emp) {

        buttonGroupAgua = new javax.swing.ButtonGroup();
        buttonGroupConoceNacimiento = new javax.swing.ButtonGroup();
        buttonGroupNumeroCrias=new javax.swing.ButtonGroup();
        jPanelRegistroLote = new javax.swing.JPanel();
        jLabelNumeroLote = new javax.swing.JLabel();
        jLabelAgua = new javax.swing.JLabel();
        jLabelRazaLote = new javax.swing.JLabel();
        jLabelImageRegistrarLote = new javax.swing.JLabel();
 
        jLabelLinea3 = new javax.swing.JLabel();
        jLabelLinea4 = new javax.swing.JLabel();
        jLabelRegistrarLote = new javax.swing.JLabel();
        jLabelPasto = new javax.swing.JLabel();
        jRadioButtonNO = new javax.swing.JRadioButton();
        jRadioButtonSI = new javax.swing.JRadioButton();
        jSpinnerNumeroLote = new javax.swing.JSpinner();
        jButtonRegistroUbicacion = new javax.swing.JButton();
        jButtonRegistrarLote = new javax.swing.JButton();
        jComboBoxCalidadPasto = new javax.swing.JComboBox<>();
        jComboBoxRazaLote = new javax.swing.JComboBox<>();
        jPanelRegistroAnimal = new javax.swing.JPanel();
        jLabelRegistrarAnimal = new javax.swing.JLabel();
        jLabelLinea1 = new javax.swing.JLabel();
        jLabelLinea2 = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelImageRegistrarAnimal = new javax.swing.JLabel();
        jLabelRaza = new javax.swing.JLabel();
        jLabePeso = new javax.swing.JLabel();
        jLabelNombreAnimal = new javax.swing.JLabel();
        jLabelTipoSexo = new javax.swing.JLabel();
        jLabelNumCrias = new javax.swing.JLabel();
        jLabelNumeroRegistro = new javax.swing.JLabel();
        jLabeCantidadCarne = new javax.swing.JLabel();
        jLabeCantidadLeche = new javax.swing.JLabel();
        jTextFieldCantidadLeche = new javax.swing.JTextField();
        jTextFieldCantidadCarne = new javax.swing.JTextField();
        jTextFieldNumeroRegistro = new javax.swing.JTextField();
        jComboBoxTipoRaza = new javax.swing.JComboBox<>();
        jComboBoxTipoSexo = new javax.swing.JComboBox<>();
        jTextFieldPesoAnimal = new javax.swing.JTextField();
        jTextFieldNombreAnimal = new javax.swing.JTextField();
        jRadioButtonNacimientoNO = new javax.swing.JRadioButton();
        jRadioButtonNacimientoSI = new javax.swing.JRadioButton();
        jRadioButtonCriasNO=new javax.swing.JRadioButton();
        jRadioButtonCriasSI=new javax.swing.JRadioButton();
        jTextFieldCrias=new javax.swing.JTextField();
        jButtonRegistrarAnimal = new javax.swing.JButton();
        jSpinnerEdad = new javax.swing.JSpinner();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabelEdad = new javax.swing.JLabel();
        jPanelRegistroUsuario = new javax.swing.JPanel();
        jLabelImageRegistrarUsuario = new javax.swing.JLabel();
        jLabelRegistrarUsuario = new javax.swing.JLabel();
        jLabelLinea5 = new javax.swing.JLabel();
        jLabelLinea6 = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabeFechaInicioLaboral = new javax.swing.JLabel();
        jLabeContraseña = new javax.swing.JLabel();
        jLabelImageUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jButtonVerContraseñaRegistroUsuario = new javax.swing.JButton();
        jComboBoxTipoUsuarioRegistro = new javax.swing.JComboBox<>();
        jPasswordFieldContraseñaRegistro = new javax.swing.JPasswordField();
        jTextFieldAuxiliarContraseña = new javax.swing.JTextField();
        jTextFieldNombreUsuarioRegistro = new javax.swing.JTextField();
        jButtonRegistrarUsuario = new javax.swing.JButton();
        jDateChooserInicioLaboral = new com.toedter.calendar.JDateChooser();
        jSpinnerSalario = new javax.swing.JSpinner();
        jPanelRegistroBotones = new javax.swing.JPanel();
        jLabeQueDeseaReguistrar = new javax.swing.JLabel();
        jButtonIrAPanelLote = new javax.swing.JButton();
        jButtonIrAPanelUsuario = new javax.swing.JButton();
        jButtonIrAPanelAnimal = new javax.swing.JButton();
        jButtonVolverVentanaPrincipal = new javax.swing.JButton();
        jLabelImageRegistrarUsuario2 = new javax.swing.JLabel();
        jPanelInicial = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muu Seguro");
        setLocation(new java.awt.Point(150, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        empresa=emp;
        
        ((javax.swing.JTextField)jDateChooserInicioLaboral.getDateEditor()).setEditable(false);
        ((javax.swing.JTextField)jDateChooserFechaNacimiento.getDateEditor()).setEditable(false);
        ((javax.swing.JSpinner.NumberEditor)jSpinnerEdad.getEditor()).getTextField().setEditable(false);
        ((javax.swing.JSpinner.NumberEditor)jSpinnerNumeroLote.getEditor()).getTextField().setEditable(false);
        
        jDateChooserInicioLaboral.getJCalendar().setMaxSelectableDate(new Date());
        jDateChooserFechaNacimiento.getJCalendar().setMaxSelectableDate(new Date());
        
        jDateChooserInicioLaboral.setDate(new Date());
        jDateChooserFechaNacimiento.setDate(new Date());
        
        
        jPanelRegistroUsuario.setVisible(false);
        jPanelRegistroAnimal.setVisible(false);
        jPanelRegistroLote.setVisible(false);
        jSpinnerEdad.setVisible(false);
        jLabelEdad.setVisible(false);
        jDateChooserFechaNacimiento.setVisible(false);
        holder=new PlaceHolder(jTextFieldNombreUsuarioRegistro,"Crear nombre de usuario");
        holder=new PlaceHolder(jPasswordFieldContraseñaRegistro,"Crear contraseña");
        holder=new PlaceHolder(jTextFieldNumeroRegistro,"##########");
        holder=new PlaceHolder(jTextFieldNombreAnimal,"Opcional");
        holder=new PlaceHolder(jTextFieldPesoAnimal,"Kilogramos");
        holder=new PlaceHolder(jTextFieldCantidadCarne,"Kilogramos");
        holder=new PlaceHolder(jTextFieldCantidadLeche,"Litros");
        holder=new PlaceHolder(jTextFieldCrias,"#registro,#registro,...");
        
        jPanelRegistroLote.setBackground(new java.awt.Color(104, 191, 52));
        jPanelRegistroLote.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      

        jLabelNumeroLote.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelNumeroLote.setForeground(new java.awt.Color(97, 97, 97));
        jLabelNumeroLote.setText("Numero de lote");
        jPanelRegistroLote.add(jLabelNumeroLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 224, 110, -1));

        jLabelAgua.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelAgua.setForeground(new java.awt.Color(97, 97, 97));
        jLabelAgua.setText("¿Punto de agua?");
        jPanelRegistroLote.add(jLabelAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 110, 20));

        jLabelRazaLote.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelRazaLote.setForeground(new java.awt.Color(97, 97, 97));
        jLabelRazaLote.setText("Raza ");
        jPanelRegistroLote.add(jLabelRazaLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 224, 100, -1));

        jLabelImageRegistrarLote.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\registroLote.png")); // NOI18N
        jPanelRegistroLote.add(jLabelImageRegistrarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, 150));

        

        jLabelLinea3.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\linea.png")); // NOI18N
        jPanelRegistroLote.add(jLabelLinea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 115, 20));

        jLabelLinea4.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\linea.png")); // NOI18N
        jPanelRegistroLote.add(jLabelLinea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 115, 20));

        jLabelRegistrarLote.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelRegistrarLote.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarLote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarLote.setText("Registrar lote");
        jLabelRegistrarLote.setToolTipText("");
        jPanelRegistroLote.add(jLabelRegistrarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, 40));

        jLabelPasto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelPasto.setForeground(new java.awt.Color(97, 97, 97));
        jLabelPasto.setText("Calidad del pasto");
        jPanelRegistroLote.add(jLabelPasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 224, 100, -1));

        jRadioButtonNO.setBackground(new java.awt.Color(97, 97, 97));
        buttonGroupAgua.add(jRadioButtonNO);
        jRadioButtonNO.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButtonNO.setText("NO");
        jRadioButtonNO.setContentAreaFilled(false);
        jPanelRegistroLote.add(jRadioButtonNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 60, -1));

        jRadioButtonSI.setBackground(new java.awt.Color(97, 97, 97));
        buttonGroupAgua.add(jRadioButtonSI);
        jRadioButtonSI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButtonSI.setText("SI");
        jRadioButtonSI.setContentAreaFilled(false);
        jPanelRegistroLote.add(jRadioButtonSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 50, -1));
            
        jButtonRegistroUbicacion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonRegistroUbicacion.setForeground(new java.awt.Color(97, 97, 97));
        jButtonRegistroUbicacion.setText("Rgistrar ubicación");
        jButtonRegistroUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroUbicacionActionPerformed(evt);
            }
        });
        jPanelRegistroLote.add( jButtonRegistroUbicacion,new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 345, 150, 30));
        
        jSpinnerNumeroLote.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        jPanelRegistroLote.add(jSpinnerNumeroLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 30));

        jButtonRegistrarLote.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonRegistrarLote.setForeground(new java.awt.Color(97, 97, 97));
        jButtonRegistrarLote.setText("Continuar");
        jButtonRegistrarLote.setToolTipText("");
        jButtonRegistrarLote.setBorder(null);
        jButtonRegistrarLote.setBorderPainted(false);
        jButtonRegistrarLote.setFocusPainted(false);
        jButtonRegistrarLote.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonRegistrarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarLoteActionPerformed(evt);
            }
        });
        jPanelRegistroLote.add(jButtonRegistrarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 329, 32));

        jComboBoxCalidadPasto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxCalidadPasto.setForeground(new java.awt.Color(97, 97, 97));
        jComboBoxCalidadPasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buena", "Regular", "Mala" }));
        jPanelRegistroLote.add(jComboBoxCalidadPasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 130, 30));

        jComboBoxRazaLote.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxRazaLote.setForeground(new java.awt.Color(97, 97, 97));
        jComboBoxRazaLote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Holstein", "Normando", "Jersey" }));
        jPanelRegistroLote.add(jComboBoxRazaLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, 30));

        getContentPane().add(jPanelRegistroLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 510, 600));

        jPanelRegistroAnimal.setBackground(new java.awt.Color(104, 191, 52));
        jPanelRegistroAnimal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistrarAnimal.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelRegistrarAnimal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarAnimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarAnimal.setText("Registrar animal");
        jLabelRegistrarAnimal.setToolTipText("");
        jPanelRegistroAnimal.add(jLabelRegistrarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, 40));

        jLabelLinea1.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\linea.png")); // NOI18N
        jPanelRegistroAnimal.add(jLabelLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 115, 20));

        jLabelLinea2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\linea.png")); // NOI18N
        jPanelRegistroAnimal.add(jLabelLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 115, 20));

        jLabelFechaNacimiento.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelFechaNacimiento.setForeground(new java.awt.Color(97, 97, 97));
        jLabelFechaNacimiento.setText("¿Conoce fecha de nacimiento?");
        jPanelRegistroAnimal.add(jLabelFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 332, 190, -1));

        jLabelImageRegistrarAnimal.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\registroAnimal.png")); // NOI18N
        jPanelRegistroAnimal.add(jLabelImageRegistrarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 150));

        jLabelRaza.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelRaza.setForeground(new java.awt.Color(97, 97, 97));
        jLabelRaza.setText("Raza");
        jPanelRegistroAnimal.add(jLabelRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 332, 130, -1));

        jLabePeso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabePeso.setForeground(new java.awt.Color(97, 97, 97));
        jLabePeso.setText("Peso");
        jPanelRegistroAnimal.add(jLabePeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 384, 134, -1));

        jLabelNombreAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelNombreAnimal.setForeground(new java.awt.Color(97, 97, 97));
        jLabelNombreAnimal.setText("Nombre de animal");
        jPanelRegistroAnimal.add(jLabelNombreAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 274, 130, -1));

        jLabelTipoSexo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelTipoSexo.setForeground(new java.awt.Color(97, 97, 97));
        jLabelTipoSexo.setText("Sexo");
        jPanelRegistroAnimal.add(jLabelTipoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 224, 30, -1));

        jLabelNumCrias.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelNumCrias.setForeground(new java.awt.Color(97, 97, 97));
        jLabelNumCrias.setText("¿Tiene crías?");
        jPanelRegistroAnimal.add(jLabelNumCrias, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 384, 134, -1));

        jLabelNumeroRegistro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelNumeroRegistro.setForeground(new java.awt.Color(97, 97, 97));
        jLabelNumeroRegistro.setText("Número de registro");
        jPanelRegistroAnimal.add(jLabelNumeroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 224, 130, -1));

        jLabeCantidadCarne.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabeCantidadCarne.setForeground(new java.awt.Color(97, 97, 97));
        jLabeCantidadCarne.setText("Cantidad de carne");
        jPanelRegistroAnimal.add(jLabeCantidadCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 444, 134, -1));

        jLabeCantidadLeche.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabeCantidadLeche.setForeground(new java.awt.Color(97, 97, 97));
        jLabeCantidadLeche.setText("Cantidad de leche");
        jPanelRegistroAnimal.add(jLabeCantidadLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 444, 134, -1));

        jTextFieldCantidadLeche.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldCantidadLeche.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldCantidadLeche.setAutoscrolls(false);
        jTextFieldCantidadLeche.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldCantidadLeche.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldCantidadLeche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadLecheKeyPressed(evt);
            }
        });
        jPanelRegistroAnimal.add(jTextFieldCantidadLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 460, 192, 30));

        jTextFieldCantidadCarne.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldCantidadCarne.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldCantidadCarne.setAutoscrolls(false);
        jTextFieldCantidadCarne.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldCantidadCarne.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldCantidadCarne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadCarneKeyPressed(evt);
            }
        });
        jPanelRegistroAnimal.add(jTextFieldCantidadCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 460, 193, 30));

        jTextFieldNumeroRegistro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldNumeroRegistro.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldNumeroRegistro.setAutoscrolls(false);
        jTextFieldNumeroRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldNumeroRegistro.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldNumeroRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroRegistroKeyPressed(evt);
            }
        });
        jPanelRegistroAnimal.add(jTextFieldNumeroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 235, 30));

       

        jComboBoxTipoRaza.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxTipoRaza.setForeground(new java.awt.Color(97, 97, 97));
        jComboBoxTipoRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Holstein", "Normando", "Jersey" }));
        jComboBoxTipoRaza.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxTipoRaza.setFocusable(false);
        jPanelRegistroAnimal.add(jComboBoxTipoRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 350, 130, 30));

        jComboBoxTipoSexo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxTipoSexo.setForeground(new java.awt.Color(97, 97, 97));
        ArrayList <String>sexos=new ArrayList<>();
        System.out.print(empresa.mdarTipoEmp());
        if(empresa.mdarTipoEmp().equals("Leche")){
            sexos.add("Vaca");
            sexos.add("Toro");
        }else{
            sexos.add("Vaca");
            sexos.add("Toro");
        }
        String [] def=sexos.toArray(new String[sexos.size()]);
        jComboBoxTipoSexo.setModel(new javax.swing.DefaultComboBoxModel<>(def));
        jComboBoxTipoSexo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxTipoSexo.setFocusable(false);
        jComboBoxTipoSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoSexoActionPerformed(evt);
            }
        });
        jPanelRegistroAnimal.add(jComboBoxTipoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 240, 150, 30));

        jTextFieldPesoAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldPesoAnimal.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldPesoAnimal.setAutoscrolls(false);
        jTextFieldPesoAnimal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldPesoAnimal.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldPesoAnimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesoAnimalKeyPressed(evt);
            }
        });
        jPanelRegistroAnimal.add(jTextFieldPesoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 400, 205, 30));

        jTextFieldNombreAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldNombreAnimal.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldNombreAnimal.setAutoscrolls(false);
        jTextFieldNombreAnimal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldNombreAnimal.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldNombreAnimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreAnimalKeyTyped(evt);
            }
        });
        jPanelRegistroAnimal.add(jTextFieldNombreAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 290, 400, 30));

        buttonGroupConoceNacimiento.add(jRadioButtonNacimientoNO);
        jRadioButtonNacimientoNO.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButtonNacimientoNO.setText("NO");
        jRadioButtonNacimientoNO.setContentAreaFilled(false);
        jRadioButtonNacimientoNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNacimientoNOActionPerformed(evt);
            }
        });
        jPanelRegistroAnimal.add(jRadioButtonNacimientoNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        buttonGroupConoceNacimiento.add(jRadioButtonNacimientoSI);
        jRadioButtonNacimientoSI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButtonNacimientoSI.setText("SI");
        jRadioButtonNacimientoSI.setContentAreaFilled(false);
        jRadioButtonNacimientoSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNacimientoSIActionPerformed(evt);
            }
        });
        jPanelRegistroAnimal.add(jRadioButtonNacimientoSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));
        
        buttonGroupNumeroCrias.add(jRadioButtonCriasNO);
        jRadioButtonCriasNO.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButtonCriasNO.setText("NO");
        jRadioButtonCriasNO.setContentAreaFilled(false);
        jRadioButtonCriasNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCriasNOActionPerformed(evt);
            }
        });
        jPanelRegistroAnimal.add(jRadioButtonCriasNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 384, -1, -1));

        buttonGroupNumeroCrias.add(jRadioButtonCriasSI);
        jRadioButtonCriasSI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButtonCriasSI.setText("SI");
        jRadioButtonCriasSI.setContentAreaFilled(false);
        jRadioButtonCriasSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCriasSIActionPerformed(evt);
            }
        });
        jPanelRegistroAnimal.add(jRadioButtonCriasSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 384, -1, -1));
  
        //Now1
        jTextFieldCrias.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldCrias.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldCrias.setAutoscrolls(false);
        jTextFieldCrias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldCrias.setEditable(false);
        jTextFieldCrias.setVisible(false);
        jPanelRegistroAnimal.add(jTextFieldCrias,new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 400, 180, 30));
        
        jButtonRegistrarAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonRegistrarAnimal.setForeground(new java.awt.Color(97, 97, 97));
        jButtonRegistrarAnimal.setText("Continuar");
        jButtonRegistrarAnimal.setToolTipText("");
        jButtonRegistrarAnimal.setBorder(null);
        jButtonRegistrarAnimal.setBorderPainted(false);
        jButtonRegistrarAnimal.setFocusPainted(false);
        jButtonRegistrarAnimal.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonRegistrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarAnimalActionPerformed(evt);
            }
        });
        jPanelRegistroAnimal.add(jButtonRegistrarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 329, 32));

        jSpinnerEdad.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jSpinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        jSpinnerEdad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSpinnerEdad.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerEdad, ""));
        jPanelRegistroAnimal.add(jSpinnerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 350, 150, 30));

        jDateChooserFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserFechaNacimiento.setForeground(new java.awt.Color(97, 97, 97));
        jPanelRegistroAnimal.add(jDateChooserFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 350, 260, 30));

        jLabelEdad.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(97, 97, 97));
        jLabelEdad.setText("Edad");
        jPanelRegistroAnimal.add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 358, 40, -1));

        getContentPane().add(jPanelRegistroAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 510, 600));

        jPanelRegistroUsuario.setBackground(new java.awt.Color(104, 191, 52));
        jPanelRegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImageRegistrarUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\registroUsuario.png")); // NOI18N
        jPanelRegistroUsuario.add(jLabelImageRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, 150));

        jLabelRegistrarUsuario.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarUsuario.setText("Registrar usuario");
        jLabelRegistrarUsuario.setToolTipText("");
        jPanelRegistroUsuario.add(jLabelRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, 40));

        jLabelLinea5.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\linea.png")); // NOI18N
        jPanelRegistroUsuario.add(jLabelLinea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 115, 20));

        jLabelLinea6.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\linea.png")); // NOI18N
        jPanelRegistroUsuario.add(jLabelLinea6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 115, 20));

        jLabelSalario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelSalario.setForeground(new java.awt.Color(97, 97, 97));
        jLabelSalario.setText("Salario");
        jPanelRegistroUsuario.add(jLabelSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 324, 130, -1));

        jLabeFechaInicioLaboral.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabeFechaInicioLaboral.setForeground(new java.awt.Color(97, 97, 97));
        jLabeFechaInicioLaboral.setText("Inicio vinculación laboral");
        jPanelRegistroUsuario.add(jLabeFechaInicioLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 426, 200, -1));

        jLabeContraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabeContraseña.setForeground(new java.awt.Color(97, 97, 97));
        jLabeContraseña.setText("Crear contraseña");
        jPanelRegistroUsuario.add(jLabeContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 374, 130, -1));

        jLabelImageUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\UsersRegistro.png")); // NOI18N
        jPanelRegistroUsuario.add(jLabelImageUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 293, 30, -1));

        jLabelNombreUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(97, 97, 97));
        jLabelNombreUsuario.setText("Nombre de usuario");
        jPanelRegistroUsuario.add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 274, 130, -1));

        jLabelTipoUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelTipoUsuario.setForeground(new java.awt.Color(97, 97, 97));
        jLabelTipoUsuario.setText("Tipo de usuario");
        jPanelRegistroUsuario.add(jLabelTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 212, 130, -1));

        jButtonVerContraseñaRegistroUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\verContraseñaUsuario.png")); // NOI18N
        jButtonVerContraseñaRegistroUsuario.setContentAreaFilled(false);
        jButtonVerContraseñaRegistroUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVerContraseñaRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerContraseñaRegistroUsuarioActionPerformed(evt);
            }
        });
        jPanelRegistroUsuario.add(jButtonVerContraseñaRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 390, 30, 30));

        jComboBoxTipoUsuarioRegistro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxTipoUsuarioRegistro.setForeground(new java.awt.Color(97, 97, 97));
        jComboBoxTipoUsuarioRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Veterinario" }));
        jComboBoxTipoUsuarioRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxTipoUsuarioRegistro.setFocusable(false);
        jPanelRegistroUsuario.add(jComboBoxTipoUsuarioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 329, 30));

        jPasswordFieldContraseñaRegistro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPasswordFieldContraseñaRegistro.setForeground(new java.awt.Color(97, 97, 97));
        jPasswordFieldContraseñaRegistro.setToolTipText("");
        jPasswordFieldContraseñaRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseñaRegistroKeyTyped(evt);
            }
        });
        jPanelRegistroUsuario.add(jPasswordFieldContraseñaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 329, 32));

        jTextFieldAuxiliarContraseña.setEditable(false);
        jTextFieldAuxiliarContraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldAuxiliarContraseña.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldAuxiliarContraseña.setAutoscrolls(false);
        jTextFieldAuxiliarContraseña.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldAuxiliarContraseña.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanelRegistroUsuario.add(jTextFieldAuxiliarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 329, 30));

        jTextFieldNombreUsuarioRegistro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldNombreUsuarioRegistro.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldNombreUsuarioRegistro.setAutoscrolls(false);
        jTextFieldNombreUsuarioRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldNombreUsuarioRegistro.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldNombreUsuarioRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreUsuarioRegistroKeyTyped(evt);
            }
        });
        jPanelRegistroUsuario.add(jTextFieldNombreUsuarioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 329, 30));

        jButtonRegistrarUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonRegistrarUsuario.setForeground(new java.awt.Color(97, 97, 97));
        jButtonRegistrarUsuario.setText("Continuar");
        jButtonRegistrarUsuario.setToolTipText("");
        jButtonRegistrarUsuario.setBorder(null);
        jButtonRegistrarUsuario.setBorderPainted(false);
        jButtonRegistrarUsuario.setFocusPainted(false);
        jButtonRegistrarUsuario.setMargin(new java.awt.Insets(100, 2, 100, 14));
        jButtonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarUsuarioActionPerformed(evt);
            }
        });
        jPanelRegistroUsuario.add(jButtonRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 329, 32));
        jPanelRegistroUsuario.add(jDateChooserInicioLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 442, 329, 30));

        jSpinnerSalario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jSpinnerSalario.setModel(new javax.swing.SpinnerNumberModel(400000, 400000, 2147483647, 10000));
        jSpinnerSalario.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerSalario, ""));
        jPanelRegistroUsuario.add(jSpinnerSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 329, 30));

        getContentPane().add(jPanelRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 510, 600));

        jPanelRegistroBotones.setBackground(new java.awt.Color(0, 51, 51));
        jPanelRegistroBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeQueDeseaReguistrar.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        jLabeQueDeseaReguistrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabeQueDeseaReguistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeQueDeseaReguistrar.setText("<html><center>¿Qué deseas registrar? ");
        jLabeQueDeseaReguistrar.setToolTipText("");
        jPanelRegistroBotones.add(jLabeQueDeseaReguistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 370, 60));

        jButtonIrAPanelLote.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButtonIrAPanelLote.setText("LOTE");
        jButtonIrAPanelLote.setForeground(new java.awt.Color(255,255,255));
        jButtonIrAPanelLote.setBorder(null);
        jButtonIrAPanelLote.setBorderPainted(false);
        jButtonIrAPanelLote.setBackground(new java.awt.Color(0, 51, 51));
        jButtonIrAPanelLote.setContentAreaFilled(false);
        jButtonIrAPanelLote.setOpaque(true);
        jButtonIrAPanelLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrAPanelLoteActionPerformed(evt);
            }
        });
        jButtonIrAPanelLote.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt,jButtonIrAPanelLote);
            }
            public void mouseExited(java.awt.event.MouseEvent evt){
                buttonMouseExited(evt, jButtonIrAPanelLote);
            }
        });
        jPanelRegistroBotones.add(jButtonIrAPanelLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 344, 200, 32));

        jButtonIrAPanelUsuario.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButtonIrAPanelUsuario.setText("USUARIO");
        jButtonIrAPanelUsuario.setForeground(new java.awt.Color(255,255,255));
        jButtonIrAPanelUsuario.setBorder(null);
        jButtonIrAPanelUsuario.setBorderPainted(false);
        jButtonIrAPanelUsuario.setBackground(new java.awt.Color(0, 51, 51));
        jButtonIrAPanelUsuario.setContentAreaFilled(false);
        jButtonIrAPanelUsuario.setOpaque(true);
        jButtonIrAPanelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrAPanelUsuarioActionPerformed(evt);
            }
        });
        
        jButtonIrAPanelUsuario.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt,jButtonIrAPanelUsuario);
            }
            public void mouseExited(java.awt.event.MouseEvent evt){
                buttonMouseExited(evt, jButtonIrAPanelUsuario);
            }
        });
        jPanelRegistroBotones.add(jButtonIrAPanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 220, 200, 32));

        jButtonIrAPanelAnimal.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButtonIrAPanelAnimal.setText("ANIMAL");
        jButtonIrAPanelAnimal.setForeground(new java.awt.Color(255,255,255));
        jButtonIrAPanelAnimal.setBorder(null);
        jButtonIrAPanelAnimal.setBorderPainted(false);
        jButtonIrAPanelAnimal.setBackground(new java.awt.Color(0, 51, 51));
        jButtonIrAPanelAnimal.setContentAreaFilled(false);
        jButtonIrAPanelAnimal.setOpaque(true);
        jButtonIrAPanelAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrAPanelAnimalActionPerformed(evt);
            }
        });
        jButtonIrAPanelAnimal.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt,jButtonIrAPanelAnimal);
            }
            public void mouseExited(java.awt.event.MouseEvent evt){
                buttonMouseExited(evt, jButtonIrAPanelAnimal);
            }
        });
        jPanelRegistroBotones.add(jButtonIrAPanelAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 282, 200, 32));

        jButtonVolverVentanaPrincipal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonVolverVentanaPrincipal.setText("Volver");
        jButtonVolverVentanaPrincipal.setForeground(new java.awt.Color(255,255,255));
        jButtonVolverVentanaPrincipal.setBorder(null);
        jButtonVolverVentanaPrincipal.setBorderPainted(false);
        jButtonVolverVentanaPrincipal.setBackground(new java.awt.Color(0, 51, 51));
        jButtonVolverVentanaPrincipal.setContentAreaFilled(false);
        jButtonVolverVentanaPrincipal.setOpaque(true);
        jButtonVolverVentanaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverVentanaPrincipalActionPerformed(evt);
            }
        });
        jButtonVolverVentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt,jButtonVolverVentanaPrincipal);
            }
            public void mouseExited(java.awt.event.MouseEvent evt){
                buttonMouseExited(evt, jButtonVolverVentanaPrincipal);
            }
        });
        jPanelRegistroBotones.add(jButtonVolverVentanaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 190, 32));

        jLabelImageRegistrarUsuario2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Silva\\Desktop\\Java\\MuuuuSeguro\\src\\Interfaz\\DataImage\\fondoRegistro.png")); // NOI18N
        jLabelImageRegistrarUsuario2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanelRegistroBotones.add(jLabelImageRegistrarUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, 530));

        getContentPane().add(jPanelRegistroBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 600));

        jPanelInicial.setBackground(new java.awt.Color(104, 191, 52));
        jPanelInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 510, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    *Color Botones
    */
    private void buttonMouseEntered(java.awt.event.MouseEvent evt, javax.swing.JButton boton) {                                             
        // TODO add your handling code here:
        boton.setBackground(new java.awt.Color(119,144,144));
    }
    private void buttonMouseExited(java.awt.event.MouseEvent evt, javax.swing.JButton boton) {                                             
        // TODO add your handling code here:
        boton.setBackground(new java.awt.Color(0,51,51));
    }
    
    
    /*
    *Ver contraseña registro usuario
    */
    private void jButtonVerContraseñaRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerContraseñaRegistroUsuarioActionPerformed
        counter+=1;
        verContraseñas(jTextFieldAuxiliarContraseña,jPasswordFieldContraseñaRegistro);
    }//GEN-LAST:event_jButtonVerContraseñaRegistroUsuarioActionPerformed
    /*
    *Cambiar a panel registrar usuario
    */
    private void jButtonIrAPanelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrAPanelUsuarioActionPerformed
        // TODO add your handling code here:
        jPanelRegistroUsuario.setVisible(true);
        jPanelRegistroAnimal.setVisible(false);
        jPanelRegistroLote.setVisible(false);
        jPanelInicial.setVisible(false);
        limpiarPaneles();
    }//GEN-LAST:event_jButtonIrAPanelUsuarioActionPerformed
    /*
    *Cambiar a panel registrar animal
    */
    private void jButtonIrAPanelAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrAPanelAnimalActionPerformed
        // TODO add your handling code here:
        jPanelRegistroUsuario.setVisible(false);
        jPanelRegistroAnimal.setVisible(true);
        jPanelRegistroLote.setVisible(false);
        jPanelInicial.setVisible(false);
        limpiarPaneles();
    }//GEN-LAST:event_jButtonIrAPanelAnimalActionPerformed
    /*
    *Cambiar a panel registrar lote
    */
    private void jButtonIrAPanelLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrAPanelLoteActionPerformed
        jPanelRegistroUsuario.setVisible(false);
        jPanelRegistroAnimal.setVisible(false);
        jPanelRegistroLote.setVisible(true);
        jPanelInicial.setVisible(false);
        limpiarPaneles();
    }//GEN-LAST:event_jButtonIrAPanelLoteActionPerformed
    /*
    *Eventos para evitar el ingreso de comas
    */
    private void jTextFieldNombreUsuarioRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioRegistroKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreUsuarioRegistroKeyTyped

    private void jPasswordFieldContraseñaRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaRegistroKeyTyped
       if(ingresoCaracterSep(evt.getKeyChar())){
           JOptionPane.showMessageDialog(null, "No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldContraseñaRegistroKeyTyped

    private void jTextFieldNombreAnimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreAnimalKeyTyped
        if(ingresoCaracterSep(evt.getKeyChar())){
           JOptionPane.showMessageDialog(null,"No se permite el ingreso de este caracter", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreAnimalKeyTyped
    /*
    *Fin de eventos ingreso de comas
    */
    /*
    *Seleccion SI conoce fecha nacimiento
    */
    private void jRadioButtonNacimientoSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNacimientoSIActionPerformed
        siConoceEdad();
    }//GEN-LAST:event_jRadioButtonNacimientoSIActionPerformed
     /*
    *Seleccion NO conoce fecha nacimiento
    */
    private void jRadioButtonNacimientoNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNacimientoNOActionPerformed
        noConoceEdad();
    }//GEN-LAST:event_jRadioButtonNacimientoNOActionPerformed
    /*
    *Seleccion SI tiene crías
    */
    private void jRadioButtonCriasSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNacimientoSIActionPerformed
        jTextFieldCrias.setEditable(true);
        jTextFieldCrias.setVisible(true);
    }
    /*
    *Seleccion NO tiene crías
    */
    private void jRadioButtonCriasNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNacimientoSIActionPerformed
        jTextFieldCrias.setEditable(false);
        jTextFieldCrias.setVisible(false);
    }
    /*
    *Boton continuar registro usuarios
    */
    private void jButtonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarUsuarioActionPerformed
        
        String tipoUsuario=(String)jComboBoxTipoUsuarioRegistro.getSelectedItem();
        String nombreUsuario=jTextFieldNombreUsuarioRegistro.getText();
        String salario=""+jSpinnerSalario.getValue();
        String fecha=new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserInicioLaboral.getDate());
        String contraseña=String.valueOf(jPasswordFieldContraseñaRegistro.getPassword());
        if(noEspaciosEnBlanco(tipoUsuario) && noEspaciosEnBlanco(nombreUsuario) 
                && noEspaciosEnBlanco(salario) && noEspaciosEnBlanco(contraseña)){
            if(comprobarSiUsuarioNoExiste(tipoUsuario, nombreUsuario)){
                //Registrar usuario
                empresa.darAdmin().registrarUsuario(tipoUsuario, Integer.parseInt(salario), nombreUsuario, contraseña, fecha);
                limpiarPaneles();
            }else{
                int respuesta=JOptionPane.showOptionDialog(this,"Usuario ya existente,¿Qué desea hacer?","Atención",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[]{"Modificar","Eliminar","Cancelar"},"Cancelar");
                if(respuesta!=-1 && respuesta!=2){
                    if(respuesta==0){
                        //Modificar usuario
                        empresa.darAdmin().modificarUsuario(tipoUsuario, Integer.parseInt(salario), nombreUsuario, contraseña, fecha);
                        limpiarPaneles();
                    }else if(respuesta==1){
                        //Eliminar usuario
                        empresa.darAdmin().eliminarUsuario(tipoUsuario, nombreUsuario);
                        limpiarPaneles();
                    }
                }
            }
                
        }else{
             JOptionPane.showMessageDialog(null, "No se permiten espacios vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarUsuarioActionPerformed

    private void jTextFieldNumeroRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroRegistroKeyPressed
        if(ingresoLetrasEnteros(evt.getKeyCode())){
           JOptionPane.showMessageDialog(null, "Solo valores númericos", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
           jTextFieldNumeroRegistro.setText("");
           holder=new PlaceHolder(jTextFieldNumeroRegistro,"##########");
        }
    }//GEN-LAST:event_jTextFieldNumeroRegistroKeyPressed

    private void jTextFieldPesoAnimalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesoAnimalKeyPressed
        if(ingresoLetrasDecimales(evt.getKeyCode())){
           JOptionPane.showMessageDialog(null, "Solo valores númericos", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
           jTextFieldPesoAnimal.setText("");
           holder=new PlaceHolder(jTextFieldPesoAnimal,"Kilogramos");
        }
    }//GEN-LAST:event_jTextFieldPesoAnimalKeyPressed


    private void jTextFieldCantidadCarneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadCarneKeyPressed
        if(ingresoLetrasDecimales(evt.getKeyCode())){
           JOptionPane.showMessageDialog(null, "Solo valores númericos", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
           jTextFieldCantidadCarne.setText("");
           holder=new PlaceHolder(jTextFieldCantidadCarne,"Kilogramos");
        }
    }//GEN-LAST:event_jTextFieldCantidadCarneKeyPressed

    private void jTextFieldCantidadLecheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadLecheKeyPressed
        if(ingresoLetrasDecimales(evt.getKeyCode())){
           JOptionPane.showMessageDialog(null, "Solo valores númericos", "Advertencia", JOptionPane.WARNING_MESSAGE);
           evt.consume();
           jTextFieldCantidadLeche.setText("");
           holder=new PlaceHolder(jTextFieldCantidadLeche,"Litros");
        }
        
    }//GEN-LAST:event_jTextFieldCantidadLecheKeyPressed
    /*
    *Boton continuar registro animal
    */
    private void jButtonRegistrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarAnimalActionPerformed
        String sexo=(String)jComboBoxTipoSexo.getSelectedItem();
        String numRegistro=jTextFieldNumeroRegistro.getText();
        String nombreAnimal=jTextFieldNombreAnimal.getText();
        String raza=(String)jComboBoxTipoRaza.getSelectedItem();
        int edad;
        if(jRadioButtonNacimientoSI.isSelected()){
            edad=calcularEdad();
        }else{
            edad=(Integer)jSpinnerEdad.getValue();
        }
        String peso=jTextFieldPesoAnimal.getText();
        String numCrias=calcularNumeroDeCrias();
        System.out.println(numCrias);
        
        String cantidadCarne;
        String cantidadLeche;
        if(sexo.equals("Vaca")){
            cantidadCarne=jTextFieldCantidadCarne.getText();
            cantidadLeche=jTextFieldCantidadLeche.getText();
        }else{
            cantidadCarne=jTextFieldCantidadCarne.getText();
            cantidadLeche="0";
        }
        if (noEspaciosEnBlanco(numRegistro) && noEspaciosEnBlanco(""+peso)
            && noEspaciosEnBlanco(""+cantidadCarne) && !numCrias.equals("")
            && noEspaciosEnBlanco(""+cantidadLeche)){
            if(!numCrias.equals("-1")){                         
                if((jRadioButtonNacimientoSI.isSelected() || jRadioButtonNacimientoNO.isSelected()) && (jRadioButtonCriasSI.isSelected() || jRadioButtonCriasNO.isSelected())){
                    if(comprobarSiAnimalNoExiste(sexo, numRegistro)){
                        empresa.darAdmin().registrarAnimal(numRegistro, nombreAnimal,raza,sexo,edad,Float.parseFloat(peso),Integer.parseInt(numCrias),Float.parseFloat(cantidadCarne),Float.parseFloat(cantidadLeche));
                        limpiarPaneles();
                    }else{
                        int respuesta=JOptionPane.showOptionDialog(this,"Animal ya existente,¿Qué desea hacer?","Atención",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[]{"Modificar","Eliminar","Cancelar"},"Cancelar");
                        if(respuesta!=-1 && respuesta!=2){
                            if(respuesta==0){
                                //Modificar animal
                                empresa.darAdmin().modificarAnimal(numRegistro, nombreAnimal,raza,sexo,edad,Float.parseFloat(peso),Integer.parseInt(numCrias),Float.parseFloat(cantidadCarne),Float.parseFloat(cantidadLeche));
                                limpiarPaneles();
                            }else if(respuesta==1){
                                //Eliminar animal
                                empresa.darAdmin().eliminarAnimal(sexo, numRegistro);
                                limpiarPaneles();
                            }
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Seleccione una opción", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                 JOptionPane.showMessageDialog(null, "Uno de los terneros ingresados no esta registrado", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }
        }else{
            JOptionPane.showMessageDialog(null, "No se permiten espacios vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarAnimalActionPerformed
    /*
    *Desaparecer cantidad leche
    */
    private void jComboBoxTipoSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoSexoActionPerformed
       if(((String)jComboBoxTipoSexo.getSelectedItem()).equals("Toro")){
           jTextFieldCantidadLeche.setVisible(false);
           jLabeCantidadLeche.setVisible(false);
       }else{
           jTextFieldCantidadLeche.setVisible(true);
           jLabeCantidadLeche.setVisible(true);
       }
    }//GEN-LAST:event_jComboBoxTipoSexoActionPerformed
    /*
    *Boton registro ubicación
    */
    private void jButtonRegistroUbicacionActionPerformed(java.awt.event.ActionEvent evt){
        //this.setEnabled(false);
        Tabla_Lotes tab=new Tabla_Lotes(this, empresa);
    }
    
    /*
    *Boton continuar registro lote
    */
    private void jButtonRegistrarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarLoteActionPerformed
       int numeroLote=(Integer)jSpinnerNumeroLote.getValue();
       
       String razaLote=(String)jComboBoxRazaLote.getSelectedItem();
       String calidadPasto=(String)jComboBoxCalidadPasto.getSelectedItem();
       String puntoAgua="";
       int x=xValueLote;
       int y=yValueLote;
       if(jRadioButtonSI.isSelected()){
           puntoAgua="SI";
       }else if(jRadioButtonNO.isSelected()){
           puntoAgua="NO";
       }
       if(jRadioButtonSI.isSelected() || jRadioButtonNO.isSelected()){
            if(x!=-1 && y!=-1){
               if(comprobarSiLoteNoExiste(numeroLote)){
                    xValueLote=-1;
                    yValueLote=-1;
                    empresa.darAdmin().registrarLote(numeroLote, razaLote, calidadPasto, puntoAgua, x,y);
                    JOptionPane.showMessageDialog(null, "Lote registrado exitosamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                    limpiarPaneles();
                }else{
                    int respuesta=JOptionPane.showOptionDialog(this,"Lote ya existente,¿Qué desea hacer?","Atención",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[]{"Modificar","Eliminar","Cancelar"},"Cancelar");
                     if(respuesta!=-1 && respuesta!=2){
                         if(respuesta==0){
                             //Modificar Lote
                             empresa.darAdmin().modificarLote(numeroLote, razaLote, calidadPasto, puntoAgua,x,y);
                             limpiarPaneles();
                         }else if(respuesta==1){
                             //Eliminar lote
                             empresa.darAdmin().eliminarLote(numeroLote);
                             limpiarPaneles();
                         }
                     }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Seleccion la ubicación", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } 
       }else{
           JOptionPane.showMessageDialog(null, "Seleccion una opción", "Advertencia", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_jButtonRegistrarLoteActionPerformed

    private void jButtonVolverVentanaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverVentanaPrincipalActionPerformed
        // TODO add your handling code here:
        limpiarPaneles();
         Ventana ventanaPrincipalAdmin=new Ventana(empresa);
         this.setVisible(false);
         ventanaPrincipalAdmin.setVisible(true);
        
    }//GEN-LAST:event_jButtonVolverVentanaPrincipalActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*
    *Objeto para tener textFields con contenido presdeterminad
    */
    private PlaceHolder holder;
    /*
    *contador para ver contraseñas
    */
    private int counter;
    /*
    *Formato para fecha
    */
    /*
    *Empresa
    */
    private Empresa empresa;
    
    
    
    private boolean noEspaciosEnBlanco(String cadena){
        if (!cadena.equals("Crear nombre de usuario") && !cadena.equals("No inferior a $400.000")
            && !cadena.equals("Crear contraseña") && !cadena.equals("##########")
            && !cadena.equals("Kilogramos") && !cadena.equals("Litros") 
            && !cadena.equals("#registro,#registro,...")){
            return true;
        }else{
            return false;
        }
    }

     /*
    *ver las contraseñas de los JPasswordField
    */
    private void verContraseñas(javax.swing.JTextField auxiliar, javax.swing.JPasswordField panelContraseña ){
        if(counter%2!=0){
            panelContraseña.setVisible(false);
            auxiliar.setVisible(true);
            auxiliar.setText(panelContraseña.getText());
        }else{
            panelContraseña.setVisible(true);
            auxiliar.setVisible(false);
        }
    }
    /*
    *Ingreso de comas
    */
    private boolean ingresoCaracterSep(char caracter){
        if(caracter==','){    
            return true;
        }
        return false;
    }
    /*
    *Ingreso de letras en espacios numericos enteros
    */
    private boolean ingresoLetrasEnteros(int code){
        int[] keyCodePermitidos={8,48,49,50,51,52,53,54,55,56,57,96,97,
                                 98,99,100,101,102,103,104,105};
        for(int i=0; i<keyCodePermitidos.length;i++){
            if(code==keyCodePermitidos[i]){
                return false;
            }
        }
        return true;
    }
    /*
    *Ingreso de letras en espacios numericos decimales
    */
     private boolean ingresoLetrasDecimales(int code){
        int[] keyCodePermitidos={8,48,49,50,51,52,53,54,55,56,57,96,97,
                                 98,99,100,101,102,103,104,105,46,110};
        for(int i=0; i<keyCodePermitidos.length;i++){
            if(code==keyCodePermitidos[i]){
                return false;
            }
        }
        return true;
    }
    
    /*
    *Comprobar si el usuario ingresado es un usuario exisente
    */
    private boolean comprobarSiUsuarioNoExiste(String tipo, String nombre){
        if(tipo.equals("Empleado")){
            if(empresa.darAdmin().comprobarSiEmpleadoExiste(nombre)){
                return false;
            }else{
                return true;
            }
        }else{
            if(empresa.darAdmin().comprobarSiVeterinarioExiste(nombre)){
                return false;
            }else{
                return true;
            }
        }
    }
    /*
    *Comprobar si el animal ingresado es un animal exisente
    */
    private boolean comprobarSiAnimalNoExiste(String sexo, String numeroReg){
        if(sexo.equals("Vaca")){
            if(empresa.darAdmin().comprobarSiVacaExiste(numeroReg)){
                return false;
            }else{
                return true;
            }
        }else{
            if(empresa.darAdmin().comprobarSiToroExiste(numeroReg)){
                return false;
            }else{
                return true;
            }
        }
    }
    
    private boolean comprobarSiAnimalExiste(String numeroReg){
    
        if(empresa.darAdmin().comprobarSiVacaExiste(numeroReg) || empresa.darAdmin().comprobarSiToroExiste(numeroReg)){
            return true;
        }else{
            return false;
           }       
    }
    /*
    *Comprobar si el lote ingresado es un lote exisente
    */
    private boolean comprobarSiLoteNoExiste(int numero){
        if(empresa.darAdmin().comprobarSiLoteExiste(numero)){
            return false;
        }else{
            return true;
        }
    }
    
    
    /*
    *Seleccion SI conoces fecha animal
    */
    private void siConoceEdad(){
        jSpinnerEdad.setVisible(false);
        jDateChooserFechaNacimiento.setVisible(true);
        jLabelEdad.setVisible(false);
    }
    /*
    *Seleccion NO conoces fecha animal
    */
    private void noConoceEdad(){
        jSpinnerEdad.setVisible(true);
        jLabelEdad.setVisible(true);
        jDateChooserFechaNacimiento.setVisible(false);
    }
    /*
    *Selección SI tienen crías
    */
   
    /*
    *Selección NO tienen crías
    */
    
    private String calcularNumeroDeCrias(){
        if(jRadioButtonCriasSI.isSelected()){
            if(noEspaciosEnBlanco(jTextFieldCrias.getText())){
                System.err.println(jTextFieldCrias.getText()+"Now");
                String []numerosSerie=jTextFieldCrias.getText().split(",");
                int aux=0;
                for(int i=0; i<numerosSerie.length; i++){
                    if(comprobarSiAnimalExiste(numerosSerie[i])){
                        aux+=1;
                    }else{
                        return "-1";
                    }  
                }
                if(aux==numerosSerie.length){
                    
                    return aux+"";
                }
            }else{
                return "";
            }
        }else{
            return "0";
        }
      return "";
    }
    private int calcularEdad(){
        LocalDate fechaNacimiento = LocalDate.parse(new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserFechaNacimiento.getDate()), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        Period periodo = Period.between(fechaNacimiento,LocalDate.now());
        return periodo.getMonths();
    }
    
    private void limpiarPaneles(){
        jTextFieldNombreUsuarioRegistro.setText("");
        jPasswordFieldContraseñaRegistro.setText("");
        jTextFieldAuxiliarContraseña.setText("");
        jDateChooserInicioLaboral.setDate(new Date());
        jDateChooserFechaNacimiento.setDate(new Date());
        jTextFieldNumeroRegistro.setText("");
        jTextFieldNombreAnimal.setText("");
        jTextFieldPesoAnimal.setText("");
        jTextFieldCantidadCarne.setText("");
        jTextFieldCantidadLeche.setText("");
        jTextFieldCrias.setText("");
        holder=new PlaceHolder(jTextFieldNombreUsuarioRegistro,"Crear nombre de usuario");
        holder=new PlaceHolder(jPasswordFieldContraseñaRegistro,"Crear contraseña");
        holder=new PlaceHolder(jTextFieldNumeroRegistro,"##########");
        holder=new PlaceHolder(jTextFieldNombreAnimal,"Opcional");
        holder=new PlaceHolder(jTextFieldPesoAnimal,"Kilogramos");
        holder=new PlaceHolder(jTextFieldCantidadCarne,"Kilogramos");
        holder=new PlaceHolder(jTextFieldCantidadLeche,"Litros"); 
        holder=new PlaceHolder(jTextFieldCrias,"#registro,#registro,...");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAgua;
    private javax.swing.ButtonGroup buttonGroupConoceNacimiento;
    private javax.swing.ButtonGroup buttonGroupNumeroCrias;
    private javax.swing.JButton jButtonIrAPanelAnimal;
    private javax.swing.JButton jButtonIrAPanelLote;
    private javax.swing.JButton jButtonIrAPanelUsuario;
    private javax.swing.JButton jButtonRegistrarAnimal;
    private javax.swing.JButton jButtonRegistrarLote;
    private javax.swing.JButton jButtonRegistrarUsuario;
    private javax.swing.JButton jButtonVerContraseñaRegistroUsuario;
    private javax.swing.JButton jButtonVolverVentanaPrincipal;
    private javax.swing.JButton jButtonRegistroUbicacion; 
    private javax.swing.JComboBox<String> jComboBoxCalidadPasto;
    private javax.swing.JComboBox<String> jComboBoxRazaLote;
    private javax.swing.JComboBox<String> jComboBoxTipoRaza;
    private javax.swing.JComboBox<String> jComboBoxTipoSexo;
    private javax.swing.JComboBox<String> jComboBoxTipoUsuarioRegistro;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private com.toedter.calendar.JDateChooser jDateChooserInicioLaboral;
    private javax.swing.JLabel jLabeCantidadCarne;
    private javax.swing.JLabel jLabeCantidadLeche;
    private javax.swing.JLabel jLabeContraseña;
    private javax.swing.JLabel jLabeFechaInicioLaboral;
    private javax.swing.JLabel jLabePeso;
    private javax.swing.JLabel jLabeQueDeseaReguistrar;
    private javax.swing.JLabel jLabelAgua;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelImageRegistrarAnimal;
    private javax.swing.JLabel jLabelImageRegistrarLote;
    private javax.swing.JLabel jLabelImageRegistrarUsuario;
    private javax.swing.JLabel jLabelImageRegistrarUsuario2;
    private javax.swing.JLabel jLabelImageUsuario;
    private javax.swing.JLabel jLabelLinea1;
    private javax.swing.JLabel jLabelLinea2;
    private javax.swing.JLabel jLabelLinea3;
    private javax.swing.JLabel jLabelLinea4;
    private javax.swing.JLabel jLabelLinea5;
    private javax.swing.JLabel jLabelLinea6;
    private javax.swing.JLabel jLabelNombreAnimal;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelNumCrias;
    private javax.swing.JLabel jLabelNumeroLote;
    private javax.swing.JLabel jLabelNumeroRegistro;
    private javax.swing.JLabel jLabelPasto;
    private javax.swing.JLabel jLabelRaza;
    private javax.swing.JLabel jLabelRazaLote;
    private javax.swing.JLabel jLabelRegistrarAnimal;
    private javax.swing.JLabel jLabelRegistrarLote;
    private javax.swing.JLabel jLabelRegistrarUsuario;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTipoSexo;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JPanel jPanelRegistroAnimal;
    private javax.swing.JPanel jPanelRegistroBotones;
    private javax.swing.JPanel jPanelRegistroLote;
    private javax.swing.JPanel jPanelRegistroUsuario;
    private javax.swing.JPasswordField jPasswordFieldContraseñaRegistro;
    private javax.swing.JRadioButton jRadioButtonNO;
    private javax.swing.JRadioButton jRadioButtonNacimientoNO;
    private javax.swing.JRadioButton jRadioButtonNacimientoSI;
    private javax.swing.JRadioButton jRadioButtonSI;
    private javax.swing.JRadioButton jRadioButtonCriasNO;
    private javax.swing.JRadioButton jRadioButtonCriasSI;
    private javax.swing.JSpinner jSpinnerEdad;
    private javax.swing.JSpinner jSpinnerNumeroLote;
    private javax.swing.JSpinner jSpinnerSalario;
    private javax.swing.JTextField jTextFieldAuxiliarContraseña;
    private javax.swing.JTextField jTextFieldCantidadCarne;
    private javax.swing.JTextField jTextFieldCantidadLeche;
    private javax.swing.JTextField jTextFieldNombreAnimal;
    private javax.swing.JTextField jTextFieldNombreUsuarioRegistro;
    private javax.swing.JTextField jTextFieldNumeroRegistro;
    private javax.swing.JTextField jTextFieldPesoAnimal;
    private javax.swing.JTextField jTextFieldCrias;
    public static int xValueLote=-1;
    public static int yValueLote=-1;

    // End of variables declaration//GEN-END:variables
}

